######################################################################
# Automatically generated by qmake (3.0) Wed. Feb. 15 16:39:49 2017
######################################################################

QT += core gui widgets xml

TEMPLATE = app
TARGET = ShapeDrawing
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h Shapes.h
FORMS += MainWindow.ui
SOURCES += main.cpp MainWindow.cpp
